In [ ]:
import numpy as np

In [3]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([7, 8, 9, 10])

In [4]:
print(v1+v2)

[ 8 10 12 14]


In [5]:
print(v1 - v2)

[-6 -6 -6 -6]


In [6]:
np.linalg.norm(v1)

5.477225575051661

In [8]:
np.linalg.norm(v2)

17.146428199482248

In [10]:
np.linalg.norm(v1,2)

5.477225575051661

In [12]:
np.linalg.norm(v2,2)

17.146428199482248

In [13]:
np.linalg.norm(v1,1)

10.0

In [14]:
np.linalg.norm(v2,1)

34.0

In [19]:
v3 = np.array([2,8,5,-19])

In [17]:
from math import inf

In [20]:
np.linalg.norm(v3, inf)

19.0

In [21]:
y = np.arange(0,15)

In [22]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
y_hat = y * 0.3

In [24]:
y_hat

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2])

In [26]:
e = y_hat-y

In [27]:
e

array([ 0. , -0.7, -1.4, -2.1, -2.8, -3.5, -4.2, -4.9, -5.6, -6.3, -7. ,
       -7.7, -8.4, -9.1, -9.8])

In [28]:
np.linalg.norm(e)**2/e.shape[0]

33.15666666666667

In [31]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [34]:
mean_absolute_error(y_hat,y)

4.9

In [32]:
mean_squared_error(y_hat,y)

33.15666666666667

In [36]:
np.linalg.norm(e,1)/e.shape[0]

4.9