In [2]:
import numpy as np

In [3]:
v1 = np.array([2,5])

In [5]:
v2  = np.array([3,4])

In [4]:
np.linalg.norm(v1)

5.385164807134504

In [6]:
np.linalg.norm(v2)

5.0

In [7]:
v1@v2

26

In [8]:
v1.shape

(2,)

In [9]:
v3 = np.array([[2,3,4]])

In [10]:
v4 = np.array([[1],
               [6],
               [7]])

In [11]:
v3.shape

(1, 3)

In [12]:
v3@v4

array([[48]])

In [13]:
v5 = np.array([[11],
               [48],
               [71]])

In [15]:
v4.T@v5

array([[796]])

In [16]:
B = np.array([[11],
              [23]])

In [17]:
A = np.array([[2,4],
              [-9,6]])

In [18]:
Aug = np.concatenate((A,B), axis=1)

In [19]:
Aug

array([[ 2,  4, 11],
       [-9,  6, 23]])

In [20]:
import sympy as sm 

In [23]:
m = sm.Matrix(Aug)

In [24]:
m.rref()

(Matrix([
 [1, 0, -13/24],
 [0, 1, 145/48]]),
 (0, 1))

In [25]:
# x -2y =1
#3x - 6y = 3

m2 = sm.Matrix([[1,-2,1],
                [3,-6,3]])

In [27]:
m2.rref()

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]),
 (0,))